import Head from 'next/head'
import Footer from '../Components/Footer'
import Navbar from '../Components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <h1 className='text-3xl font-bold'>AirBnB KW</h1>
        <Card /> */}
        <Navbar />
      </main>
      <Footer />
    </div>
  )
}
