import Head from 'next/head'
import Footer from '../Components/Footer'
import Navbar from '../Components/Navbar'
import HomePage from './home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </div>
  )
}
